name: test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  fmt:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-python@v4
      with:
        python-version: "3.12"
    - uses: Gr1N/setup-poetry@v8
    - run: poetry install
    - name: Test with pytest
      run: |
        poetry run ruff format --check

  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-python@v4
      with:
        python-version: "3.12"
    - uses: Gr1N/setup-poetry@v8
    - run: poetry install
    - name: Test with pytest
      run: |
        poetry run ruff check

  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-python@v4
      with:
        python-version: "3.12"
    - uses: Gr1N/setup-poetry@v8
    - run: poetry install
    - uses: prefix-dev/setup-pixi@v0.8.1
    - run: |
        pixi global install -c Gurobi gurobi
    - name: Test with pytest
      run: |
        poetry run pytest -v
